DI_Praktika/Models/Query/QueryCreateVM.cs
using DI_Praktika.Data.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DI_Praktika.Models.Query
{
    public class QueryCreateVM
    {
        private DateTime start = DateTime.Now;
        private DateTime end = DateTime.Now;

        [Required]
        public DateTime Start 
        {
            get
            {
                return start;
            }
            set
            {
                start = value;
            }
        }

        [Required]
        public DateTime End 
        {
            get
            {
                return end;
            }
            set
            {
                if (value < this.Start)
                {
                    throw new Exception();
                }
                else
                {
                    end = value;
                }
            }
        }
        [Required]
        public string CarID { get; set; }
        public ICollection<Data.Entities.Car> Cars { get; set; }
        public string User { get; set; }
        [Required]
        public double Price { get; set; }
        [Required]
        public string Status { get; set; }
        public ICollection<Status> StatusObject { get; set; }
        public string Message { get; set; }
        public bool IsFirstTime { get; set; }
    }
}

DI_Praktika/Models/Query/QueryEditVM.cs
using DI_Praktika.Data.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DI_Praktika.Models.Query
{
    public class QueryEditVM
    {
        private DateTime start = DateTime.Now;
        private DateTime end = DateTime.Now;

        public string ID { get; set; }
        [Required]
        public DateTime Start
        {
            get
            {
                return start;
            }
            set
            {
                start = value;
            }
        }

        [Required]
        public DateTime End
        {
            get
            {
                return end;
            }
            set
            {
                if (value < this.Start)
                {
                    throw new Exception();
                }
                else
                {
                    end = value;
                }
            }
        }
        [Required]
        public string CarID { get; set; }
        public ICollection<Data.Entities.Car> Cars { get; set; }
        public string User { get; set; }
        [Required]
        public double Price { get; set; }
        [Required]
        public string Status { get; set; }
        public ICollection<Status> StatusObject { get; set; }
    }
}

DI_Praktika/Models/Query/QueryIndexVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DI_Praktika.Models.Query
{
    public class QueryIndexVM
    {
        public ICollection<QueryVM> Items { get; set; }
    }
}

DI_Praktika/Models/Query/QueryVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DI_Praktika.Models.Query
{
    public class QueryVM
    {
        public string ID { get; set; }
        public DateTime Start { get; set; }
        public DateTime End { get; set; }
        public string Car { get; set; }
        public double Price { get; set; }
        public string Status { get; set; }
        public string User { get; set; }
    }
}

DI_Praktika/Controllers/QueryController.cs
using DI_Praktika.Data;
using DI_Praktika.Data.Entities;
using DI_Praktika.Models.Query;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DI_Praktika.Controllers
{
    [Authorize(Roles = "Administrator, Client")]
    public class QueryController : Controller
    {
        private readonly ApplicationDbContext db;

        public QueryController()
        {
            db = new ApplicationDbContext();
        }

        public IActionResult Index()
        {
            List<Query> queries = db.Queries.ToList();
            List<QueryVM> list = new List<QueryVM>();

            foreach (var query in queries)
            {
                if(query.End <= DateTime.Now)
                {
                    query.Status = db.Statuses.Where(s => s.Name == "Overdue").FirstOrDefault().ID;
                    db.Update(query);
                    db.SaveChanges();
                }

                list.Add(new QueryVM()
                {
                    ID = query.ID,
                    Start = query.Start,
                    End = query.End,
                    Car = db.Cars.Find(query.carID).ToString(),
                    Price = query.Price,
                    Status = db.Statuses.Find(query.Status).Name,
                    User = db.Users.Where(u => u.Id == query.userID).FirstOrDefault().UserName
                });
            }

            QueryIndexVM model = new QueryIndexVM()
            {
                Items = list
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            QueryCreateVM model = new QueryCreateVM()
            {
                Cars = db.Cars.ToList(),
                StatusObject = db.Statuses.ToList()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(QueryCreateVM model)
        {
            List<Query> list = db.Queries.Where(q => q.carID == model.CarID).ToList();
            bool isFree = true;

            foreach (var query in list)
            {
                if(query.Start <= model.Start && query.End >= model.Start)
                {
                    isFree = false;
                    break;
                }
            }

            if (isFree)
            {
                if (ModelState.IsValid)
                {
                    Query query = new Query()
                    {
                        ID = Guid.NewGuid().ToString(),
                        carID = model.CarID,
                        userID = db.Users.Where(u => u.UserName == model.User).FirstOrDefault().Id,
                        End = model.End,
                        Start = model.Start,
                        Price = model.Price,
                        Status = model.Status
                    };

                    db.Queries.Add(query);

                    await db.SaveChangesAsync();

                    return RedirectToAction("Index");
                }
            }
            else
            {
                model.IsFirstTime = false;
                model.Cars = db.Cars.ToList();
                model.StatusObject = db.Statuses.ToList();

                model.Message = "The car is not free.";
                return View(model);
            }


            return View();
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            Query query = db.Queries.Find(id);

            QueryEditVM model = new QueryEditVM()
            {
                ID = query.ID,
                CarID = query.carID,
                End = query.End,
                Start = query.Start,
                Price = query.Price,
                Status = query.Status,
                Cars = db.Cars.ToList(),
                User = query.userID,
                StatusObject = db.Statuses.ToList()
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(QueryEditVM model)
        {
            if (ModelState.IsValid)
            {
                Query query = db.Queries.Find(model.ID);

                query.carID = model.CarID;
                query.End = model.End;
                query.Start = model.Start;
                query.Price = model.Price;
                query.Status = model.Status;

                try
                {
                    db.Update(query);
                    db.SaveChanges();
                }
                catch (Exception)
                {
                    bool isExist = db.Cars.Any(f => f.ID == query.ID);

                    if (!isExist)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Delete(string id)
        {
            Query query = db.Queries.Find(id);

            db.Remove(query);

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Canceled(string id)
        {
            Query query = db.Queries.Find(id);
            query.Status = db.Statuses.Where(s => s.Name == "Canceled").FirstOrDefault().ID;
            db.Update(query);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

DI_Praktika/Views/Query/Create.cshtml
@model DI_Praktika.Models.Query.QueryCreateVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Query" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div>
                <label asp-for="Start" class="control-label"></label>
                <input asp-for="Start" class="form-control" />
                <span asp-validation-for="Start" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="End" class="control-label"></label>
                <input asp-for="End" class="form-control" />
                <span asp-validation-for="End" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="CarID" class="control-label"></label>
                <select asp-for="CarID" class="form-control">
                    @foreach (var item in Model.Cars)
                    {
                        <option value="@item.ID">@item.ToString()</option>
                    }
                </select>
            </div>
            <div>
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control">
                    @foreach (var item in Model.StatusObject)
                    {
                        <option value="@item.ID">@item.Name</option>
                    }
                </select>
            </div>
            <div hidden>
                <label asp-for="User" class="control-label"></label>
                <input asp-for="User" value="@User.Identity.Name" class="form-control" />
                <span asp-validation-for="User" class="text-danger"></span>
            </div>
            @if (!Model.IsFirstTime)
            {
                <div class="alert">
                    <p>@Model.Message</p>
                </div>
            }
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back</a>
</div>

DI_Praktika/Views/Query/Edit.cshtml
@model DI_Praktika.Models.Query.QueryEditVM 

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="Query" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div>
                <label asp-for="Start" class="control-label"></label>
                <input asp-for="Start" class="form-control" />
                <span asp-validation-for="Start" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="End" class="control-label"></label>
                <input asp-for="End" class="form-control" />
                <span asp-validation-for="End" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="CarID" class="control-label"></label>
                <select asp-for="CarID" class="form-control">
                    @foreach (var item in Model.Cars)
                    {
                        <option value="@item.ID">@item.Brand "@item.Model" @item.Year</option>
                    }
                </select>
            </div>
            <div>
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control">
                    @foreach (var item in Model.StatusObject)
                    {
                        <option value="@item.ID">@item.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back</a>
</div>

DI_Praktika/Views/Query/Index.cshtml
@model DI_Praktika.Models.Query.QueryIndexVM

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<div>
    <a asp-action="Create">Create New</a>
</div>

<table id="table" class="table table-striped">
    <thead>
        <tr>
            <th>Start</th>
            <th>End</th>
            <th>Car</th>
            <th>Price</th>
            <th>Status</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.Items)
        {
            if ((item.User == User.Identity.Name && User.IsInRole("Client")) || (User.IsInRole("Administrator")))
            {
        <tr>
            <td>@Html.DisplayFor(m => item.Start)</td>
            <td>@Html.DisplayFor(m => item.End)</td>
            <td>@Html.DisplayFor(m => item.Car)</td>
            <td>@Html.DisplayFor(m => item.Price)</td>
            <td>@Html.DisplayFor(m => item.Status)</td>
            @if (DateTime.Now < item.Start)
            {
                <td><a asp-action="Canceled" asp-route-id="@item.ID" class="btn btn-primary">Canceled</a></td>
            }
            <td><a asp-action="Edit" asp-route-id="@item.ID" class="btn btn-primary">Edit</a></td>
            <td><a asp-action="Delete" asp-route-id="@item.ID" class="btn btn-danger">Delete</a></td>
        </tr>
            }
        }
    </tbody>
</table>