DI_Praktika/Controllers/AdminController.cs
using DI_Praktika.Data;
using DI_Praktika.Data.Entities;
using DI_Praktika.Models.UserViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DI_Praktika.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
        {
            private UserManager<User> _userManager;
            private readonly RoleManager<IdentityRole> _roleManager;
            private IPasswordHasher<User> _passwordHasher;
            private ApplicationDbContext _dbContext;

            public AdminController(UserManager<User> userManager, RoleManager<IdentityRole> roleManager, IPasswordHasher<User> passwordHasher, ApplicationDbContext dbContext)
            {
                this._userManager = userManager;
                this._roleManager = roleManager;
                this._passwordHasher = passwordHasher;
                this._dbContext = dbContext;
            }

            public async Task<IActionResult> UserList()
            {
                var users = await _userManager.Users.ToListAsync();
                var getAllUsersViewModel = new List<GetAllUsersViewModel>();

                foreach (User user in users)
                {
                    var allUsersVM = new GetAllUsersViewModel
                    {
                        UserId = user.Id,
                        Username = user.UserName,
                        FirstName = user.FirstName,
                        MiddleName = user.MiddleName,
                        LastName = user.LastName,
                        Email = user.Email,
                        PersonPIN = user.PersonID,
                        PhoneNumber = user.PhoneNumber,
                        Roles = await GetUserRoles(user)
                    };
                    getAllUsersViewModel.Add(allUsersVM);
                }
                return View(getAllUsersViewModel);
            }

            private async Task<List<string>> GetUserRoles(User user)
            {
                return new List<string>(await _userManager.GetRolesAsync(user));
            }

            [HttpGet]
            public IActionResult Create()
            {
                CreateUserViewModel model = new CreateUserViewModel();
                var roles = _roleManager.Roles.ToList();
                ViewBag.Roles = new SelectList(roles, "Id", "Name");

                return View(model);
            }

            [HttpPost]
            public async Task<IActionResult> Create(CreateUserViewModel createUser)
            {
                if (ModelState.IsValid)
                {
                    User appUser = new User
                    {
                        Id = Guid.NewGuid().ToString(),
                        UserName = createUser.Username,
                        FirstName = createUser.FirstName,
                        MiddleName = createUser.MiddleName,
                        LastName = createUser.LastName,
                        Email = createUser.Email,
                        PhoneNumber = createUser.PhoneNumber,
                        PersonID = createUser.PersonPIN,
                    };
                    var result = await _userManager.CreateAsync(appUser, createUser.Password);

                    if (result.Succeeded)
                    {
                        var currentUser = _userManager.FindByIdAsync(appUser.Id);
                        var role = _roleManager.FindByIdAsync(createUser.Roles).Result;
                        await _userManager.AddToRoleAsync(appUser, role.Name);
                        _dbContext.SaveChanges();

                        return RedirectToAction("Index");

                    }
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
                return RedirectToAction("Index");
            }

            [HttpGet]
            public async Task<IActionResult> Edit(string id)
            {
                User user = await _userManager.FindByIdAsync(id);
                if (user == null)
                {
                    ViewBag.ErrorMessage = $"User with Id = {id} cannot be found";
                    return NotFound();
                }


                var userViewModel = new EditUserViewModel
                {
                    UserId = user.Id,
                    Username = user.UserName,
                    MiddleName = user.MiddleName,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    Email = user.Email,
                    PersonPIN = user.PersonID,
                    PhoneNumber = user.PhoneNumber,
                };

                return View(userViewModel);
            }

            public async Task<IActionResult> Edit(EditUserViewModel userViewModel)
            {
                var user = await _userManager.FindByIdAsync(userViewModel.UserId);

                if (user == null)
                {
                    ViewBag.ErrorMessage = $"User with Id = {userViewModel.UserId} cannot be found";
                    return NotFound();
                }
                else
                {
                    user.UserName = userViewModel.Username;
                    user.FirstName = userViewModel.FirstName;
                    user.LastName = userViewModel.LastName;
                    user.Email = userViewModel.Email;
                    user.PersonID = userViewModel.PersonPIN;
                    user.PhoneNumber = userViewModel.PhoneNumber;

                    var result = await _userManager.UpdateAsync(user);
                    _dbContext.SaveChanges();

                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }

                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }

                    return RedirectToAction("Index");
                }
            }
            public async Task<IActionResult> Delete(string id)
            {
                User appUser = await _userManager.FindByIdAsync(id);

                if (appUser != null)
                {
                    IdentityResult result = await _userManager.DeleteAsync(appUser);
                    await _dbContext.SaveChangesAsync();

                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return NotFound();
                    }

                }
                else
                {
                    ModelState.AddModelError("", "User not found");
                }
                return RedirectToAction("Index");
            }
        }
    
}

DI_Praktika/Controllers/CarController.cs
using DI_Praktika.Data;
using DI_Praktika.Data.Entities;
using DI_Praktika.Models.Car;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace DI_Praktika.Controllers
{
    public class CarController : Controller
    {
        private readonly ApplicationDbContext db;

        public CarController()
        {
            db = new ApplicationDbContext();
        }

        [Authorize(Roles = "Administrator, Client")]
        public IActionResult Index()
        {
            CarIndexVM model = new CarIndexVM()
            {
                Items = db.Cars.ToList()
            };

            return View(model);
        }

        [Authorize(Roles = "Administrator")]
        [HttpGet]
        public IActionResult Create()
        {
            CarCreateVM model = new CarCreateVM();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CarCreateVM model)
        {
            if (ModelState.IsValid)
            {
                Car car = new Car()
                {
                    ID = Guid.NewGuid().ToString(),
                    Brand = model.Brand,
                    Model = model.CarModel,
                    Description = model.Description,
                    PriceForRentForDay = model.PriceForRentForDay,
                    PassangersCount = model.PassangersCount,
                    Year = model.Year,
                    Photo = SaveFile(model.Photo)
                };

                db.Add<Car>(car);
                await db.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View(model);
        }

        private static string SaveFile(IFormFile file)
        {
            var fileName = Path.GetFileName(file.FileName);
            var extension = fileName.Split('.').Last();
            var fileNameWithoutExtension = string.Join("", fileName.Split('.').Take(fileName.Length - 1));

            var newfileName = "wwwroot/images/" + String.Format("{0}-{1:ddMMYYYYHHmmss}.{2}",
                fileNameWithoutExtension,
                DateTime.Now,
                extension
            );

            if (!Directory.Exists(Path.GetDirectoryName(newfileName)))
            {
                Directory.CreateDirectory(Path.GetDirectoryName(newfileName));
            }

            using (var localFile = System.IO.File.OpenWrite(newfileName))
            {
                using (var uploadedFile = file.OpenReadStream())
                {
                    uploadedFile.CopyTo(localFile);
                }
            }

            return newfileName;
        }

        [Authorize(Roles = "Administrator")]
        [HttpGet]
        public IActionResult Edit(string? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            Car model = db.Cars.Find(id);

            if(model == null)
            {
                return NotFound();
            }

            CarEditVM car = new CarEditVM()
            {
                ID = model.ID,
                Brand = model.Brand,
                CarModel = model.Model,
                Description = model.Description,
                PriceForRentForDay = model.PriceForRentForDay,
                PassangersCount = model.PassangersCount,
                Year = model.Year,
                Photo = model.Photo
            };

            return View(car);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CarEditVM model)
        {
            if (ModelState.IsValid)
            {
                Car car = db.Cars.FindAsync(model.ID).Result;

                car.Brand = model.Brand;
                car.Model = model.CarModel;
                car.Description = model.Description;
                car.PriceForRentForDay = model.PriceForRentForDay;
                car.PassangersCount = model.PassangersCount;
                car.Year = model.Year;
                car.Photo = model.Photo;

                try
                {
                    db.Update(car);
                    await db.SaveChangesAsync();
                }
                catch (Exception)
                {
                    bool isExist = db.Cars.Any(f => f.ID == car.ID);

                    if (!isExist)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction("Index");
            }

            return View();
        }

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(string? id)
        {
            Car car = await db.Cars.FindAsync(id);
            db.Cars.Remove(car);

            await db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Administrator, Client")]
        public IActionResult SeeACar(string id)
        {
            SeeACarVM model = new SeeACarVM()
            {
                Src = db.Cars.Find(id).Photo
            };

            return View(model);
        }
    }
}

DI_Praktika/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DI_Praktika</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4-4.1.1/dt-1.10.24/b-1.7.0/date-1.0.3/fc-3.3.2/fh-3.1.8/r-2.2.7/sc-2.0.3/sb-1.0.1/sp-1.2.2/sl-1.3.3/datatables.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DI_Praktika</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="UserList">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Query" asp-action="Index">Queries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Index">Cars</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - DI_Praktika - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4-4.1.1/dt-1.10.24/b-1.7.0/date-1.0.3/fc-3.3.2/fh-3.1.8/r-2.2.7/sc-2.0.3/sb-1.0.1/sp-1.2.2/sl-1.3.3/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>